import './style.css'

// import './topics/01-basic-typs'
// import './topics/02-objetcs-interfaces'
// import './topics/03-function'
// import './topics/ejercicios/01-ejercicios'
// import './topics/05-destructuracion_arreglos'
// import './topics/06-Destructuracion_argumentos'
// import './topics/07-import-export'
// import './topics/08-clases-basicas'
// import './topics/09-genericos'
// import './topics/09-genericos'
// import './topics/10-decoradores'
import './topics/11-encadenamiento-opcional'

